services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\MediaLibrary\Validation\Service\UploadedFileValidatorChainInterface:
    class: OxidEsales\MediaLibrary\Validation\Service\UploadedFileValidatorChain
    public: true
    arguments:
      $fileValidators:
        - '@OxidEsales\MediaLibrary\Validation\Validator\FileUploadStatusValidator'

  OxidEsales\MediaLibrary\Validation\Validator\FileUploadStatusValidator: ~
