services:
  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Language: '@=service("OxidEsales\\MediaLibrary\\Core\\Registry").getLang()'
      OxidEsales\Eshop\Core\Utils: '@=service("OxidEsales\\MediaLibrary\\Core\\Registry").getUtils()'

  OxidEsales\MediaLibrary\Transition\Core\LanguageInterface:
    class: OxidEsales\MediaLibrary\Transition\Core\LanguageProxy
    public: true

  OxidEsales\MediaLibrary\Transition\Core\ResponseInterface:
    class: OxidEsales\MediaLibrary\Transition\Core\Response
    public: true